/** @type {import('jest').Config} */
module.exports = {
  testEnvironment: "jsdom",
  testMatch: ["**/*.test.ts", "**/*.test.tsx", "**/*.test.cjs"],
  setupFilesAfterEnv: ["<rootDir>/src/test-utils/setup.ts"],
  transform: {
    "^.+\\.css$": "<rootDir>/scripts/jest/cssTransform.cjs",
    "^.+\\.(ts|tsx)$": [
      "ts-jest",
      {
        tsconfig: {
          module: "commonjs",
          moduleResolution: "node",
          jsx: "react-jsx",
          jsxImportSource: "react",
          strict: true,
          noImplicitAny: true,
          target: "ES2020",
          lib: ["ES2020", "DOM"],
          types: ["node", "jest"],
        },
        diagnostics: true,
      },
    ],
  },
  moduleNameMapper: {
    "^obsidian$": "<rootDir>/src/__mocks__/obsidian.ts",
  },
  collectCoverageFrom: [
    "src/**/*.{ts,tsx}",
    "!src/__mocks__/**",
    "!src/e2e/**",
    "!src/test-utils/**",
    "!src/types/**",
    "!src/main.ts",
    "!src/ribbon/**",
    "!src/ribbon/RibbonShell.ts",
    "!src/tabs/insert/**",
    "!src/tabs/draw/**",
    "!src/tabs/history/**",
    "!src/tabs/review/**",
    "!src/tabs/view/**",
    "!src/tabs/help/**",
    "!src/shared/hooks/useRibbonState.ts",
    "!src/tabs/home/basic-text/helpers.ts",
    "!src/tabs/home/email/pdfExport.ts",
    "!src/tabs/home/email/helpers/obsidian-html/**",
    "!src/tabs/home/email/helpers/pdf-generator/**",
    "!src/tabs/home/email/helpers/send-orchestration/**",
    "!src/tabs/home/tags/customize-modal/**",
    "!src/**/*.test.ts",
    "!src/**/*.test.tsx",
    "!src/**/*.integration.ts",
    "!src/**/*.combinations.ts",
    "!src/shared/editor/styling-engine/interfaces.ts",
  ],
  coveragePathIgnorePatterns: [
    "/node_modules/",
    "/coverage/",
    "/scripts/",
    "/e2e/",
    "\\.test\\.(ts|tsx|cjs)$",
  ],
  coverageThreshold: {},
  globalTeardown: "<rootDir>/scripts/jest/per-file-coverage-threshold/perFileCoverageThreshold.cjs",
};
