export const REQUIRED_HOME_COMMANDS = [
  'paste',
  'cut',
  'copy',
  'format-painter',
  'clear-all',
  'bold',
  'italic',
  'underline',
  'strikethrough',
  'subscript',
  'superscript',
  'bullet-list-toggle',
  'number-list-toggle',
  'outdent',
  'indent',
  'delete-element',
  'highlight',
  'font-color',
  'align',
  'font-family',
  'font-size',
  'styles-prev',
  'styles-next',
  'styles-expand',
  'todo',
  'important',
  'question',
  'more-tags',
  'todo-tag',
  'find-tags',
  'email-page',
  'meeting-details',
  'outline',
  'fold-all',
  'unfold-all',
] as const;

export const EXPECTED_HOME_GROUP_NAMES = [
  'Clipboard',
  'Basic Text',
  'Styles',
  'Tags',
  'Email & Meetings',
  'Navigate',
] as const;
